# This workflow tests the siegfried.rb formula.
#
# Trigger this workflow by pushing a commit updating siegfried.rb
name: Test
on:
  push:
   # paths:
   #   - siegfried.rb
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check the formula
        run: brew install --build-from-source ./siegfried.rb
      - name: Test siegfried
        run: sf -version
