# This workflow tests the siegfried.rb formula.
#
# Trigger this workflow by pushing a commit updating siegfried.rb
name: Test
on:
  push:
   paths:
     - siegfried.rb
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: List brew installs
        run: brew list
      - name: Check the siegfried formula
        run: |
          brew remove go@1.17
          brew install richardlehane/digipres/siegfried
      - name: Test siegfried
        run: sf -version
