# This workflow tests the siegfried.rb formula.
#
# Trigger this workflow by pushing a commit updating siegfried.rb
name: Test
on:
  push:
   # paths:
   #   - siegfried.rb
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check the formula
        run: |
          brew remove go
          brew install richardlehane/digipres/siegfried
      - name: Test siegfried
        run: sf -version
